name: cd

on:
  push:
    branches: [main]

jobs:
   deploy:
    name: Deploy 
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.0"
      - name: Show go version
        run: ./scripts/buildprod.sh
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'
      - name: 'Google cloud build'
        run: 'gcloud builds submit --tag europe-central2-docker.pkg.dev/notely-490021/notely-ar-repo/notely:latest --gcs-source-staging-dir=gs://notely-490021-cloudbuild/source .'
      
